/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import control.GerInterGrafica;

import domain.*;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilh
 */
public class DlgOrdemProducao extends javax.swing.JDialog {

    
    private GerInterGrafica gerIG;
    
    public DlgOrdemProducao(java.awt.Frame parent, boolean modal, GerInterGrafica gerIG) {
        super(parent, modal);
        this.gerIG = gerIG;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdemProducao = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        btnAlterarStatus = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ordem de Produção");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordem de Produção", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tblOrdemProducao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Profissional", "Cliente ", "Data Entrega", "Valor", "Status OS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrdemProducao);

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/atualizar.png"))); // NOI18N
        btnAtualizar.setText("Atualizar Lista");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnAlterarStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterarStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/alterar.Item.png"))); // NOI18N
        btnAlterarStatus.setText("Alterar Status");
        btnAlterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarStatusActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor a Receber");

        txtValorTotal.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtualizar)
                        .addGap(46, 46, 46)
                        .addComponent(btnAlterarStatus)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarStatus)
                    .addComponent(btnAtualizar)
                    .addComponent(jLabel1)
                    .addComponent(txtValorTotal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarStatusActionPerformed
        OrdemServico ordemServicoAtualizada = null;

        int linha = tblOrdemProducao.getSelectedRow();
        if ( linha >= 0 ) {
            ordemServicoAtualizada = (OrdemServico) tblOrdemProducao.getValueAt(linha, 0);
            gerIG.abrirMostrarOS(ordemServicoAtualizada);
            carregarDados();
        }
        /*try {
            ((DefaultTableModel) tblOrdemProducao.getModel()).addRow(itemSelecionado.toArray());
        }catch (ParseException ex) {
            Logger.getLogger(DlgItem.class.getName()).log(Level.SEVERE, null, ex);
        }*/

    }//GEN-LAST:event_btnAlterarStatusActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        carregarDados();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        try {
            txtValorTotal.setText("");
            carregarDados();
        } catch (Exception ex) {
            Logger.getLogger(DlgMostrarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown
    public void carregarTabelaOrcamento(List<OrdemServico> listaOrdemServico, List<VendaAcessorio> listaVendaAcessorio) throws ParseException{
        Double valor = 0.0;
        ((DefaultTableModel) tblOrdemProducao.getModel()).setRowCount(0);    
        for (OrdemServico ordemServico : listaOrdemServico) {
            valor += ordemServico.getValotTotal();
            ((DefaultTableModel) tblOrdemProducao.getModel()).addRow(ordemServico.toArray());       
        }
        for (VendaAcessorio venda_acessorio : listaVendaAcessorio) {
            valor += venda_acessorio.getValotTotal();
            ((DefaultTableModel) tblOrdemProducao.getModel()).addRow(venda_acessorio.toArrayJanCliente());            
        }
        txtValorTotal.setText(String.valueOf(valor));
    }
    
    public void carregarDados(){
        List<OrdemServico> listaOrdemServico = new ArrayList();
        List<VendaAcessorio> listaAcessorio = new ArrayList();
        try {
            listaOrdemServico = gerIG.getGerDom().carregarOrdemServico("PRODUÇÃO", "");
            listaAcessorio = gerIG.getGerDom().carregarVendasAcessorio("TODOS", "");
            carregarTabelaOrcamento(listaOrdemServico, listaAcessorio);
        } catch (Exception ex) {
            Logger.getLogger(DlgOrdemProducao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarStatus;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblOrdemProducao;
    private javax.swing.JLabel txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
