/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import control.GerInterGrafica;
import domain.Cliente;
import domain.OrdemServico;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author guilh
 */
public class framPrincipal extends javax.swing.JFrame {

    
    private GerInterGrafica gerIG;
    
    public framPrincipal(GerInterGrafica gerIG) {
        this.gerIG = gerIG;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrcamento = new javax.swing.JButton();
        btnOrdemProducao = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        btnConfirmarOrcamento = new javax.swing.JToggleButton();
        btnVendaAcessorio = new javax.swing.JButton();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadCliente = new javax.swing.JMenuItem();
        mnuCadFunci = new javax.swing.JMenuItem();
        mnuBusca = new javax.swing.JMenu();
        mnuBuscaCliente = new javax.swing.JMenuItem();
        mnuItem = new javax.swing.JMenu();
        mnuInserirItem = new javax.swing.JMenuItem();
        mnuRelatorio = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oficina Mecânica");

        btnOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/inserir.orçamento.png"))); // NOI18N
        btnOrcamento.setText("Inserir Orçamento");
        btnOrcamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrcamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrcamentoActionPerformed(evt);
            }
        });

        btnOrdemProducao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/certo.png"))); // NOI18N
        btnOrdemProducao.setText("Ordem de Produção");
        btnOrdemProducao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrdemProducao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrdemProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdemProducaoActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnConfirmarOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/confirmarOrçamento.png"))); // NOI18N
        btnConfirmarOrcamento.setMnemonic('C');
        btnConfirmarOrcamento.setText("Confirmar Orçamento");
        btnConfirmarOrcamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfirmarOrcamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfirmarOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarOrcamentoActionPerformed(evt);
            }
        });

        btnVendaAcessorio.setText("Venda Acessórios");
        btnVendaAcessorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaAcessorioActionPerformed(evt);
            }
        });

        mnuPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        mnuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/adicionar.novos.png"))); // NOI18N
        mnuCadastro.setText("Cadastro");
        mnuCadastro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mnuCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuCadastro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnuCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/add-Cliente_MnuPop.png"))); // NOI18N
        mnuCadCliente.setText("Cliente");
        mnuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadCliente);

        mnuCadFunci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/funcionario.add.png"))); // NOI18N
        mnuCadFunci.setText("Funcionarios");
        mnuCadFunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadFunciActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadFunci);

        mnuPrincipal.add(mnuCadastro);

        mnuBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/busca.Cadastro.png"))); // NOI18N
        mnuBusca.setText("Busca");
        mnuBusca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuBusca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuBusca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnuBuscaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/buscaCliente.png"))); // NOI18N
        mnuBuscaCliente.setText("Busca Cliente");
        mnuBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscaClienteActionPerformed(evt);
            }
        });
        mnuBusca.add(mnuBuscaCliente);

        mnuPrincipal.add(mnuBusca);

        mnuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/menu.item.png"))); // NOI18N
        mnuItem.setText("Serviço");
        mnuItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuItem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuItem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnuInserirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/add.png"))); // NOI18N
        mnuInserirItem.setText("Inserir Serviço");
        mnuInserirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInserirItemActionPerformed(evt);
            }
        });
        mnuItem.add(mnuInserirItem);

        mnuPrincipal.add(mnuItem);

        mnuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/relatorio.menu.png"))); // NOI18N
        mnuRelatorio.setText("Relatorio");
        mnuRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/gerar.relatorio.png"))); // NOI18N
        jMenuItem6.setText("Relatorio de Vendas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuRelatorio.add(jMenuItem6);

        mnuPrincipal.add(mnuRelatorio);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnOrcamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrdemProducao, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                    .addComponent(btnVendaAcessorio, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarOrcamento))
                .addContainerGap(555, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVendaAcessorio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrcamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrdemProducao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmarOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadClienteActionPerformed
        gerIG.abrirJanCadCliente();
    }//GEN-LAST:event_mnuCadClienteActionPerformed

    private void mnuBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscaClienteActionPerformed
        Cliente cliente = null;
        cliente = gerIG.abrirBuscaCliente();
        if(cliente != null){
            gerIG.abrirMostrarCliente(cliente);
        }
    }//GEN-LAST:event_mnuBuscaClienteActionPerformed

    private void mnuCadFunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadFunciActionPerformed
        gerIG.abrirJanCadFuncionario();
        
    }//GEN-LAST:event_mnuCadFunciActionPerformed

    private void btnOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrcamentoActionPerformed
        try {
            OrdemServico os = null;
            gerIG.abrirOrdemServico(1, os);
        } catch (Exception ex) {
            Logger.getLogger(framPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOrcamentoActionPerformed

    private void btnOrdemProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdemProducaoActionPerformed
        gerIG.abrirOrdemProdução();
    }//GEN-LAST:event_btnOrdemProducaoActionPerformed

    private void mnuInserirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInserirItemActionPerformed
        gerIG.abrirInserirServico();
        
    }//GEN-LAST:event_mnuInserirItemActionPerformed

    private void btnConfirmarOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarOrcamentoActionPerformed
        
        gerIG.abrirBuscaOS();
        
        /*List<OrdemServico> listaOrdemServico = new ArrayList();

        try {
            listaOrdemServico = gerIG.getGerDom().carregarOrdemServico(1);
            
        } catch (Exception ex) {
            Logger.getLogger(framPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnConfirmarOrcamentoActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        gerIG.abrirRelatorioVendas();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void btnVendaAcessorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaAcessorioActionPerformed
        gerIG.abrirVendaAssesorio();
    }//GEN-LAST:event_btnVendaAcessorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConfirmarOrcamento;
    private javax.swing.JButton btnOrcamento;
    private javax.swing.JButton btnOrdemProducao;
    private javax.swing.JButton btnVendaAcessorio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu mnuBusca;
    private javax.swing.JMenuItem mnuBuscaCliente;
    private javax.swing.JMenuItem mnuCadCliente;
    private javax.swing.JMenuItem mnuCadFunci;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuInserirItem;
    private javax.swing.JMenu mnuItem;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenu mnuRelatorio;
    // End of variables declaration//GEN-END:variables
}
